# Generated by Django 4.0.2 on 2022-02-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_upvote_downvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
